apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-frontend
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: campus-frontend
  template:
    metadata:
      labels:
        app: campus-frontend
    spec:
      containers:
      - name: frontend
        image: dist_sys_app-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: campus-config
              key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: campus-frontend-service
  namespace: default
spec:
  type: ClusterIP 
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: campus-frontend